/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    '../../packages/shared/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Manrope', 'system-ui', 'sans-serif'],
        display: ['Sora', 'system-ui', 'sans-serif'],
      },
      colors: {
        dark: {
          50:  'rgb(var(--c-text-rgb) / <alpha-value>)',
          100: 'rgb(var(--c-text2-rgb) / <alpha-value>)',
          200: 'rgb(var(--c-body2-rgb) / <alpha-value>)',
          300: 'rgb(var(--c-muted2-rgb) / <alpha-value>)',
          400: 'rgb(var(--c-muted2-rgb) / <alpha-value>)',
          500: 'rgb(var(--c-muted-rgb) / <alpha-value>)',
          600: 'rgb(var(--c-border2-rgb) / <alpha-value>)',
          700: 'rgb(var(--c-border-rgb) / <alpha-value>)',
          800: 'rgb(var(--c-s2-rgb) / <alpha-value>)',
          900: 'rgb(var(--c-s1-rgb) / <alpha-value>)',
          950: 'rgb(var(--c-bg-rgb) / <alpha-value>)',
        },
        bg:       'var(--bg)',
        surface:  'var(--s1)',
        surface2: 'var(--s2)',
        'layer-border':  'var(--border)',
        'layer-border2': 'var(--border2)',
        body:     'var(--text)',
        muted:    'var(--muted)',
        muted2:   'var(--muted2)',
        accent:   'var(--pink)',
        accent2:  'var(--pink2)',
        success:  'var(--green)',
        info:     'var(--blue)',
        warning:  'var(--orange)',
        danger:   'var(--red)',
        caution:  'var(--yellow)',
        subtle:   'var(--purple)',
        // Palette emerald — Epicerie
        primary: {
          50:  '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#059669',
          600: '#047857',
          700: '#065f46',
          800: '#064e3b',
          900: '#022c22',
          950: '#011a14',
        },
      },
      keyframes: {
        'fade-in':    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'fade-out':   { '0%': { opacity: '1' }, '100%': { opacity: '0' } },
        'zoom-in-95': { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'zoom-out-95':{ '0%': { opacity: '1', transform: 'scale(1)' }, '100%': { opacity: '0', transform: 'scale(0.95)' } },
        'slide-in-from-right':  { '0%': { transform: 'translateX(100%)' }, '100%': { transform: 'translateX(0)' } },
        'slide-in-from-left':   { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(0)' } },
        'slide-in-from-top':    { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(0)' } },
        'slide-in-from-bottom': { '0%': { transform: 'translateY(100%)' }, '100%': { transform: 'translateY(0)' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'stripes': { '0%': { backgroundPosition: '0 0' }, '100%': { backgroundPosition: '40px 0' } },
        'spin':    { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        'fade-out': 'fade-out 0.2s ease-out',
        'zoom-in-95': 'zoom-in-95 0.2s ease-out',
        'zoom-out-95': 'zoom-out-95 0.2s ease-out',
        'slide-in-from-right': 'slide-in-from-right 0.3s ease-out',
        'slide-in-from-left': 'slide-in-from-left 0.3s ease-out',
        'slide-in-from-top': 'slide-in-from-top 0.3s ease-out',
        'slide-in-from-bottom': 'slide-in-from-bottom 0.3s ease-out',
        'shimmer': 'shimmer 2s infinite linear',
        'stripes': 'stripes 1s infinite linear',
        'spin': 'spin 1s linear infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
