/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FideliteRejoindreRouteImport } from './routes/fidelite/rejoindre'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppSalleRouteImport } from './routes/_app/salle'
import { Route as AppPreparationsRouteImport } from './routes/_app/preparations'
import { Route as AppMesDemandesRouteImport } from './routes/_app/mes-demandes'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppIngredientsRouteImport } from './routes/_app/ingredients'
import { Route as AppHistoriqueRouteImport } from './routes/_app/historique'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCuisineRouteImport } from './routes/_app/cuisine'
import { Route as AppCatalogueRouteImport } from './routes/_app/catalogue'
import { Route as AppBarRouteImport } from './routes/_app/bar'
import { Route as AppFideliteIndexRouteImport } from './routes/_app/fidelite/index'
import { Route as AppFideliteRewardsRouteImport } from './routes/_app/fidelite/rewards'
import { Route as AppFideliteMembresRouteImport } from './routes/_app/fidelite/membres'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FideliteRejoindreRoute = FideliteRejoindreRouteImport.update({
  id: '/fidelite/rejoindre',
  path: '/fidelite/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSalleRoute = AppSalleRouteImport.update({
  id: '/salle',
  path: '/salle',
  getParentRoute: () => AppRoute,
} as any)
const AppPreparationsRoute = AppPreparationsRouteImport.update({
  id: '/preparations',
  path: '/preparations',
  getParentRoute: () => AppRoute,
} as any)
const AppMesDemandesRoute = AppMesDemandesRouteImport.update({
  id: '/mes-demandes',
  path: '/mes-demandes',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCuisineRoute = AppCuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const AppBarRoute = AppBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => AppRoute,
} as any)
const AppFideliteIndexRoute = AppFideliteIndexRouteImport.update({
  id: '/fidelite/',
  path: '/fidelite/',
  getParentRoute: () => AppRoute,
} as any)
const AppFideliteRewardsRoute = AppFideliteRewardsRouteImport.update({
  id: '/fidelite/rewards',
  path: '/fidelite/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppFideliteMembresRoute = AppFideliteMembresRouteImport.update({
  id: '/fidelite/membres',
  path: '/fidelite/membres',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bar': typeof AppBarRoute
  '/catalogue': typeof AppCatalogueRoute
  '/cuisine': typeof AppCuisineRoute
  '/dashboard': typeof AppDashboardRoute
  '/historique': typeof AppHistoriqueRoute
  '/ingredients': typeof AppIngredientsRoute
  '/menu': typeof AppMenuRoute
  '/mes-demandes': typeof AppMesDemandesRoute
  '/preparations': typeof AppPreparationsRoute
  '/salle': typeof AppSalleRoute
  '/stock': typeof AppStockRoute
  '/fidelite/rejoindre': typeof FideliteRejoindreRoute
  '/fidelite/membres': typeof AppFideliteMembresRoute
  '/fidelite/rewards': typeof AppFideliteRewardsRoute
  '/fidelite/': typeof AppFideliteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bar': typeof AppBarRoute
  '/catalogue': typeof AppCatalogueRoute
  '/cuisine': typeof AppCuisineRoute
  '/dashboard': typeof AppDashboardRoute
  '/historique': typeof AppHistoriqueRoute
  '/ingredients': typeof AppIngredientsRoute
  '/menu': typeof AppMenuRoute
  '/mes-demandes': typeof AppMesDemandesRoute
  '/preparations': typeof AppPreparationsRoute
  '/salle': typeof AppSalleRoute
  '/stock': typeof AppStockRoute
  '/fidelite/rejoindre': typeof FideliteRejoindreRoute
  '/fidelite/membres': typeof AppFideliteMembresRoute
  '/fidelite/rewards': typeof AppFideliteRewardsRoute
  '/fidelite': typeof AppFideliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bar': typeof AppBarRoute
  '/_app/catalogue': typeof AppCatalogueRoute
  '/_app/cuisine': typeof AppCuisineRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/historique': typeof AppHistoriqueRoute
  '/_app/ingredients': typeof AppIngredientsRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/mes-demandes': typeof AppMesDemandesRoute
  '/_app/preparations': typeof AppPreparationsRoute
  '/_app/salle': typeof AppSalleRoute
  '/_app/stock': typeof AppStockRoute
  '/fidelite/rejoindre': typeof FideliteRejoindreRoute
  '/_app/fidelite/membres': typeof AppFideliteMembresRoute
  '/_app/fidelite/rewards': typeof AppFideliteRewardsRoute
  '/_app/fidelite/': typeof AppFideliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bar'
    | '/catalogue'
    | '/cuisine'
    | '/dashboard'
    | '/historique'
    | '/ingredients'
    | '/menu'
    | '/mes-demandes'
    | '/preparations'
    | '/salle'
    | '/stock'
    | '/fidelite/rejoindre'
    | '/fidelite/membres'
    | '/fidelite/rewards'
    | '/fidelite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bar'
    | '/catalogue'
    | '/cuisine'
    | '/dashboard'
    | '/historique'
    | '/ingredients'
    | '/menu'
    | '/mes-demandes'
    | '/preparations'
    | '/salle'
    | '/stock'
    | '/fidelite/rejoindre'
    | '/fidelite/membres'
    | '/fidelite/rewards'
    | '/fidelite'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bar'
    | '/_app/catalogue'
    | '/_app/cuisine'
    | '/_app/dashboard'
    | '/_app/historique'
    | '/_app/ingredients'
    | '/_app/menu'
    | '/_app/mes-demandes'
    | '/_app/preparations'
    | '/_app/salle'
    | '/_app/stock'
    | '/fidelite/rejoindre'
    | '/_app/fidelite/membres'
    | '/_app/fidelite/rewards'
    | '/_app/fidelite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FideliteRejoindreRoute: typeof FideliteRejoindreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelite/rejoindre': {
      id: '/fidelite/rejoindre'
      path: '/fidelite/rejoindre'
      fullPath: '/fidelite/rejoindre'
      preLoaderRoute: typeof FideliteRejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salle': {
      id: '/_app/salle'
      path: '/salle'
      fullPath: '/salle'
      preLoaderRoute: typeof AppSalleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preparations': {
      id: '/_app/preparations'
      path: '/preparations'
      fullPath: '/preparations'
      preLoaderRoute: typeof AppPreparationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mes-demandes': {
      id: '/_app/mes-demandes'
      path: '/mes-demandes'
      fullPath: '/mes-demandes'
      preLoaderRoute: typeof AppMesDemandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredients': {
      id: '/_app/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cuisine': {
      id: '/_app/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof AppCuisineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue': {
      id: '/_app/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar': {
      id: '/_app/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof AppBarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fidelite/': {
      id: '/_app/fidelite/'
      path: '/fidelite'
      fullPath: '/fidelite/'
      preLoaderRoute: typeof AppFideliteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fidelite/rewards': {
      id: '/_app/fidelite/rewards'
      path: '/fidelite/rewards'
      fullPath: '/fidelite/rewards'
      preLoaderRoute: typeof AppFideliteRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fidelite/membres': {
      id: '/_app/fidelite/membres'
      path: '/fidelite/membres'
      fullPath: '/fidelite/membres'
      preLoaderRoute: typeof AppFideliteMembresRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBarRoute: typeof AppBarRoute
  AppCatalogueRoute: typeof AppCatalogueRoute
  AppCuisineRoute: typeof AppCuisineRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppMenuRoute: typeof AppMenuRoute
  AppMesDemandesRoute: typeof AppMesDemandesRoute
  AppPreparationsRoute: typeof AppPreparationsRoute
  AppSalleRoute: typeof AppSalleRoute
  AppStockRoute: typeof AppStockRoute
  AppFideliteMembresRoute: typeof AppFideliteMembresRoute
  AppFideliteRewardsRoute: typeof AppFideliteRewardsRoute
  AppFideliteIndexRoute: typeof AppFideliteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBarRoute: AppBarRoute,
  AppCatalogueRoute: AppCatalogueRoute,
  AppCuisineRoute: AppCuisineRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppMenuRoute: AppMenuRoute,
  AppMesDemandesRoute: AppMesDemandesRoute,
  AppPreparationsRoute: AppPreparationsRoute,
  AppSalleRoute: AppSalleRoute,
  AppStockRoute: AppStockRoute,
  AppFideliteMembresRoute: AppFideliteMembresRoute,
  AppFideliteRewardsRoute: AppFideliteRewardsRoute,
  AppFideliteIndexRoute: AppFideliteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FideliteRejoindreRoute: FideliteRejoindreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
