"""add_users_table_for_authentication

Revision ID: 3dce6788397a
Revises: cc96cee37419
Create Date: 2026-02-12 00:41:47.534546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dce6788397a'
down_revision: Union[str, None] = 'cc96cee37419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email unique (login)'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Mot de passe haché (bcrypt)'),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment="Nom complet de l'utilisateur"),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Rôle RBAC (admin, manager, staff)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID du tenant (organisation cliente)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Actif (False = supprimé logiquement)'),
    sa.CheckConstraint("role IN ('admin', 'manager', 'staff')", name='check_user_role_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_reservation_lines_product_id'), table_name='reservation_lines')
    op.drop_index(op.f('ix_reservations_customer_id'), table_name='reservations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reservations_customer_id'), 'reservations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reservation_lines_product_id'), 'reservation_lines', ['product_id'], unique=False)
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
