"""Add Phase 2 business models (Customer, Product, Reservation, Invoice)

Revision ID: 5cc8547db975
Revises: 
Create Date: 2026-02-11 22:57:48.562055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc8547db975'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False, comment='Type de client: individual ou company'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Prénom (requis si individual)'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Nom (requis si individual)'),
    sa.Column('company_name', sa.String(length=200), nullable=True, comment='Raison sociale (requis si company)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email de contact (unique par tenant)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Téléphone de contact'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Adresse postale complète'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='Ville'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Code postal'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Pays'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID du tenant (organisation cliente)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Actif (False = supprimé logiquement)'),
    sa.CheckConstraint("(customer_type = 'individual' AND first_name IS NOT NULL AND last_name IS NOT NULL) OR (customer_type = 'company' AND company_name IS NOT NULL)", name='check_customer_data_coherence'),
    sa.CheckConstraint("customer_type IN ('individual', 'company')", name='check_customer_type_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_customer_tenant_email')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Nom du produit'),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='Code produit unique (Stock Keeping Unit)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Catégorie du produit'),
    sa.Column('price_per_day', sa.BigInteger(), nullable=False, comment='Prix location par jour en centimes (250 = 2.50€)'),
    sa.Column('deposit_amount', sa.BigInteger(), nullable=False, comment='Montant caution par unité en centimes (500 = 5€)'),
    sa.Column('stock_quantity', sa.Integer(), nullable=False, comment='Quantité totale en stock'),
    sa.Column('available_quantity', sa.Integer(), nullable=False, comment='Quantité disponible à la location'),
    sa.Column('condition', sa.String(length=20), nullable=False, comment='État du produit (neuf, bon, use, hors_service)'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment="URL de l'image du produit"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID du tenant (organisation cliente)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Actif (False = supprimé logiquement)'),
    sa.CheckConstraint("category IN ('assiette', 'verre', 'couvert', 'nappe', 'deco', 'autre')", name='check_product_category_valid'),
    sa.CheckConstraint("condition IN ('neuf', 'bon', 'use', 'hors_service')", name='check_product_condition_valid'),
    sa.CheckConstraint('available_quantity <= stock_quantity', name='check_product_available_lte_stock'),
    sa.CheckConstraint('deposit_amount >= 0', name='check_product_deposit_positive'),
    sa.CheckConstraint('price_per_day >= 0', name='check_product_price_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_product_tenant_name'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_product_tenant_sku')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='ID du client'),
    sa.Column('reference', sa.String(length=50), nullable=False, comment='Référence unique de réservation (RES-2026-0001)'),
    sa.Column('event_date', sa.Date(), nullable=False, comment="Date de l'événement"),
    sa.Column('delivery_date', sa.Date(), nullable=False, comment='Date de livraison'),
    sa.Column('return_date', sa.Date(), nullable=False, comment='Date de retour'),
    sa.Column('event_location', sa.String(length=500), nullable=True, comment="Lieu de l'événement"),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Statut de la réservation'),
    sa.Column('total_amount', sa.BigInteger(), nullable=False, comment='Montant total en centimes'),
    sa.Column('deposit_amount', sa.BigInteger(), nullable=False, comment='Montant caution en centimes'),
    sa.Column('deposit_paid', sa.Boolean(), nullable=False, comment='Caution payée'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID du tenant (organisation cliente)'),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'in_progress', 'completed', 'cancelled')", name='check_reservation_status_valid'),
    sa.CheckConstraint('delivery_date <= event_date', name='check_reservation_delivery_before_event'),
    sa.CheckConstraint('deposit_amount >= 0', name='check_reservation_deposit_positive'),
    sa.CheckConstraint('return_date >= delivery_date', name='check_reservation_return_after_delivery'),
    sa.CheckConstraint('return_date >= event_date', name='check_reservation_return_after_event'),
    sa.CheckConstraint('total_amount >= 0', name='check_reservation_total_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_reservations_tenant_id'), 'reservations', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=False, comment='ID de la réservation (one-to-one)'),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Numéro de facture unique (INV-2026-0001)'),
    sa.Column('issue_date', sa.Date(), nullable=False, comment="Date d'émission de la facture"),
    sa.Column('due_date', sa.Date(), nullable=False, comment="Date d'échéance de paiement"),
    sa.Column('total_amount', sa.BigInteger(), nullable=False, comment='Montant total en centimes'),
    sa.Column('paid_amount', sa.BigInteger(), nullable=False, comment='Montant payé en centimes'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Statut de la facture'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='Moyen de paiement (cash, card, transfer, check)'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='Date de paiement'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID du tenant (organisation cliente)'),
    sa.CheckConstraint("payment_method IS NULL OR payment_method IN ('cash', 'card', 'transfer', 'check')", name='check_invoice_payment_method_valid'),
    sa.CheckConstraint("status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')", name='check_invoice_status_valid'),
    sa.CheckConstraint('due_date >= issue_date', name='check_invoice_due_after_issue'),
    sa.CheckConstraint('paid_amount <= total_amount', name='check_invoice_paid_lte_total'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id'),
    sa.UniqueConstraint('tenant_id', 'invoice_number', name='uq_invoice_tenant_number')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('reservation_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=False, comment='ID de la réservation'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='ID du produit'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantité réservée'),
    sa.Column('unit_price', sa.BigInteger(), nullable=False, comment='Prix unitaire par jour en centimes (snapshot)'),
    sa.Column('subtotal', sa.BigInteger(), nullable=False, comment='Sous-total en centimes (quantity × unit_price)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date de dernière modification'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID du tenant (organisation cliente)'),
    sa.CheckConstraint('quantity > 0', name='check_reservation_line_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'product_id', name='uq_reservation_line_reservation_product')
    )
    op.create_index(op.f('ix_reservation_lines_tenant_id'), 'reservation_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_lines_tenant_id'), table_name='reservation_lines')
    op.drop_table('reservation_lines')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_reservations_tenant_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
