"""add_api_key_id_to_audit_logs

Revision ID: 7b215135cf65
Revises: c9d0e1f2a3b4
Create Date: 2026-02-16 22:10:44.007379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b215135cf65'
down_revision: Union[str, None] = 'c9d0e1f2a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nom descriptif de la cle API',
               existing_nullable=False)
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment='Prefixe visible pour identification (mk_live_xxxx)',
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='SHA-256 du full key',
               existing_nullable=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment='Permissions accordees (resource:action)',
               existing_nullable=False)
    op.alter_column('api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment='Limite requetes par heure (null = defaut tenant)',
               existing_nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('api_keys', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date d'expiration (null = pas d'expiration)",
               existing_nullable=True)
    op.alter_column('api_keys', 'created_by',
               existing_type=sa.BIGINT(),
               comment="ID de l'admin qui a cree la cle",
               existing_nullable=False)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de derniere utilisation',
               existing_nullable=True)
    op.alter_column('api_keys', 'last_used_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='IP de la derniere utilisation (IPv4 ou IPv6)',
               existing_nullable=True)
    op.alter_column('api_keys', 'usage_count',
               existing_type=sa.BIGINT(),
               comment="Compteur d'utilisations",
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('audit_logs', sa.Column('api_key_id', sa.BigInteger(), nullable=True, comment='ID API key (NULL si action par utilisateur ou système)'))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.BIGINT(),
               comment='ID utilisateur (NULL pour actions système automatiques ou API key)',
               existing_comment='ID utilisateur (NULL pour actions système automatiques)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Adresse IP du client (IPv4/IPv6) ou valeur test (max 45 chars)',
               existing_comment='Adresse IP du client (IPv4/IPv6 via type INET PostgreSQL)',
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_api_key_id'), 'audit_logs', ['api_key_id'], unique=False)
    op.alter_column('bundle_items', 'bundle_id',
               existing_type=sa.INTEGER(),
               comment='FK vers product_bundles',
               existing_nullable=False)
    op.alter_column('bundle_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='FK vers products',
               existing_nullable=False)
    op.alter_column('bundle_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Quantite dans le bundle',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('bundle_items', 'display_order',
               existing_type=sa.INTEGER(),
               comment="Ordre d'affichage dans le bundle",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bundle_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bundle_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bundle_items', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nom de la categorie',
               existing_nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='Slug URL-safe unique par tenant',
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=1000),
               comment='Description de la categorie',
               existing_nullable=True)
    op.alter_column('categories', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='ID de la categorie parente (NULL = racine)',
               existing_nullable=True)
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment="URL de l'image de la categorie",
               existing_nullable=True)
    op.alter_column('categories', 'display_order',
               existing_type=sa.INTEGER(),
               comment="Ordre d'affichage",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_categories_tenant_parent'), table_name='categories')
    op.drop_index(op.f('ix_categories_tenant_slug'), table_name='categories')
    op.alter_column('feature_flags', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Identifiant unique du flag (snake_case)',
               existing_nullable=False)
    op.alter_column('feature_flags', 'description',
               existing_type=sa.TEXT(),
               comment='Description humaine du flag',
               existing_nullable=True)
    op.alter_column('feature_flags', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Master switch global (False = desactive pour tous)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('feature_flags', 'target_tenants',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment='Tenant IDs cibles (null=tous, []=aucun, [1,2]=specifiques)',
               existing_nullable=True)
    op.alter_column('feature_flags', 'rollout_pct',
               existing_type=sa.INTEGER(),
               comment='Pourcentage de rollout 0-100',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('feature_flags', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Donnees arbitraires (plan, tier, config)',
               existing_nullable=True)
    op.alter_column('feature_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'feature_flags', ['name'])
    op.alter_column('inventory_movements', 'event_id',
               existing_type=sa.INTEGER(),
               comment='Référence événement (pas de FK)',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'reservation_id',
               existing_type=sa.INTEGER(),
               comment='FK réservation liée (nullable)',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Type: departure ou return',
               existing_nullable=False)
    op.alter_column('inventory_movements', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date planifiée du mouvement',
               existing_nullable=False)
    op.alter_column('inventory_movements', 'actual_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date effective du mouvement',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut: scheduled, in_transit, completed, late, cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('inventory_movements', 'delivery_method',
               existing_type=sa.VARCHAR(length=20),
               comment='Méthode: delivery, pickup, shipping',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'delivery_address',
               existing_type=sa.TEXT(),
               comment='Adresse de livraison',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'delivery_notes',
               existing_type=sa.TEXT(),
               comment='Notes de livraison',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'handled_by_user_id',
               existing_type=sa.INTEGER(),
               comment='Utilisateur responsable du mouvement',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'inspection_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Statut inspection: pending, ok, damaged, missing',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'inspection_notes',
               existing_type=sa.TEXT(),
               comment="Notes d'inspection",
               existing_nullable=True)
    op.alter_column('inventory_movements', 'damage_fee',
               existing_type=sa.BIGINT(),
               comment='Frais de dommage en centimes (0 = aucun)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('inventory_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_movements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_movements', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('inventory_movements', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('mfa_devices', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('mfa_devices', 'user_id',
               existing_type=sa.BIGINT(),
               comment='User who owns this MFA device',
               existing_nullable=False)
    op.alter_column('mfa_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mfa_devices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mfa_devices', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('movement_items', 'movement_id',
               existing_type=sa.INTEGER(),
               comment='FK mouvement parent',
               existing_nullable=False)
    op.alter_column('movement_items', 'event_item_id',
               existing_type=sa.INTEGER(),
               comment='Référence ligne événement (pas de FK)',
               existing_nullable=True)
    op.alter_column('movement_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='FK produit',
               existing_nullable=True)
    op.alter_column('movement_items', 'product_variation_id',
               existing_type=sa.INTEGER(),
               comment='Référence variation produit (pas de FK)',
               existing_nullable=True)
    op.alter_column('movement_items', 'quantity_expected',
               existing_type=sa.INTEGER(),
               comment='Quantité prévue',
               existing_nullable=False)
    op.alter_column('movement_items', 'quantity_actual',
               existing_type=sa.INTEGER(),
               comment='Quantité effective (remplie à la complétion)',
               existing_nullable=True)
    op.alter_column('movement_items', 'condition',
               existing_type=sa.VARCHAR(length=20),
               comment='État: perfect, good, damaged, missing',
               existing_nullable=True)
    op.alter_column('movement_items', 'condition_notes',
               existing_type=sa.TEXT(),
               comment="Notes sur l'état de l'article",
               existing_nullable=True)
    op.alter_column('movement_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('movement_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('movement_items', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('product_bundles', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nom du bundle',
               existing_nullable=False)
    op.alter_column('product_bundles', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='Slug URL-safe unique par tenant',
               existing_nullable=False)
    op.alter_column('product_bundles', 'description',
               existing_type=sa.TEXT(),
               comment='Description longue du bundle',
               existing_nullable=True)
    op.alter_column('product_bundles', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Description courte pour les listes',
               existing_nullable=True)
    op.alter_column('product_bundles', 'bundle_price',
               existing_type=sa.BIGINT(),
               comment='Prix du bundle en centimes (25000 = 250.00 EUR)',
               existing_nullable=False)
    op.alter_column('product_bundles', 'cleaning_fee',
               existing_type=sa.BIGINT(),
               comment='Frais de nettoyage en centimes',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('product_bundles', 'featured',
               existing_type=sa.BOOLEAN(),
               comment='Mis en avant sur le site',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_bundles', 'display_order',
               existing_type=sa.INTEGER(),
               comment="Ordre d'affichage",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_bundles', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment="URL de l'image du bundle",
               existing_nullable=True)
    op.alter_column('product_bundles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_bundles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_bundles', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('product_bundles', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_bundles_tenant_id'), table_name='product_bundles')
    op.drop_index(op.f('ix_bundles_tenant_slug'), table_name='product_bundles')
    op.create_index(op.f('ix_product_bundles_tenant_id'), 'product_bundles', ['tenant_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email unique par tenant (login)',
               existing_comment='Email unique (login)',
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment="Prénom de l'utilisateur",
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment="Nom de famille de l'utilisateur",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Nom de famille de l'utilisateur",
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Prénom de l'utilisateur",
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email unique (login)',
               existing_comment='Email unique par tenant (login)',
               existing_nullable=False)
    op.drop_index(op.f('ix_product_bundles_tenant_id'), table_name='product_bundles')
    op.create_index(op.f('ix_bundles_tenant_slug'), 'product_bundles', ['tenant_id', 'slug'], unique=False)
    op.create_index(op.f('ix_bundles_tenant_id'), 'product_bundles', ['tenant_id'], unique=False)
    op.alter_column('product_bundles', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('product_bundles', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('product_bundles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_bundles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_bundles', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment="URL de l'image du bundle",
               existing_nullable=True)
    op.alter_column('product_bundles', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Ordre d'affichage",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_bundles', 'featured',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Mis en avant sur le site',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_bundles', 'cleaning_fee',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Frais de nettoyage en centimes',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('product_bundles', 'bundle_price',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Prix du bundle en centimes (25000 = 250.00 EUR)',
               existing_nullable=False)
    op.alter_column('product_bundles', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Description courte pour les listes',
               existing_nullable=True)
    op.alter_column('product_bundles', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description longue du bundle',
               existing_nullable=True)
    op.alter_column('product_bundles', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Slug URL-safe unique par tenant',
               existing_nullable=False)
    op.alter_column('product_bundles', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nom du bundle',
               existing_nullable=False)
    op.alter_column('movement_items', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('movement_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('movement_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('movement_items', 'condition_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Notes sur l'état de l'article",
               existing_nullable=True)
    op.alter_column('movement_items', 'condition',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='État: perfect, good, damaged, missing',
               existing_nullable=True)
    op.alter_column('movement_items', 'quantity_actual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantité effective (remplie à la complétion)',
               existing_nullable=True)
    op.alter_column('movement_items', 'quantity_expected',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantité prévue',
               existing_nullable=False)
    op.alter_column('movement_items', 'product_variation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Référence variation produit (pas de FK)',
               existing_nullable=True)
    op.alter_column('movement_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK produit',
               existing_nullable=True)
    op.alter_column('movement_items', 'event_item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Référence ligne événement (pas de FK)',
               existing_nullable=True)
    op.alter_column('movement_items', 'movement_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK mouvement parent',
               existing_nullable=False)
    op.alter_column('mfa_devices', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('mfa_devices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mfa_devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mfa_devices', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='User who owns this MFA device',
               existing_nullable=False)
    op.alter_column('mfa_devices', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory_movements', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('inventory_movements', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('inventory_movements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_movements', 'damage_fee',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Frais de dommage en centimes (0 = aucun)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('inventory_movements', 'inspection_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Notes d'inspection",
               existing_nullable=True)
    op.alter_column('inventory_movements', 'inspection_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut inspection: pending, ok, damaged, missing',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'handled_by_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Utilisateur responsable du mouvement',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'delivery_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notes de livraison',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'delivery_address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Adresse de livraison',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'delivery_method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Méthode: delivery, pickup, shipping',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Statut: scheduled, in_transit, completed, late, cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.alter_column('inventory_movements', 'actual_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date effective du mouvement',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date planifiée du mouvement',
               existing_nullable=False)
    op.alter_column('inventory_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Type: departure ou return',
               existing_nullable=False)
    op.alter_column('inventory_movements', 'reservation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK réservation liée (nullable)',
               existing_nullable=True)
    op.alter_column('inventory_movements', 'event_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Référence événement (pas de FK)',
               existing_nullable=True)
    op.drop_constraint(None, 'feature_flags', type_='unique')
    op.alter_column('feature_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Donnees arbitraires (plan, tier, config)',
               existing_nullable=True)
    op.alter_column('feature_flags', 'rollout_pct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Pourcentage de rollout 0-100',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('feature_flags', 'target_tenants',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               comment=None,
               existing_comment='Tenant IDs cibles (null=tous, []=aucun, [1,2]=specifiques)',
               existing_nullable=True)
    op.alter_column('feature_flags', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Master switch global (False = desactive pour tous)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('feature_flags', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description humaine du flag',
               existing_nullable=True)
    op.alter_column('feature_flags', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Identifiant unique du flag (snake_case)',
               existing_nullable=False)
    op.create_index(op.f('ix_categories_tenant_slug'), 'categories', ['tenant_id', 'slug'], unique=False)
    op.create_index(op.f('ix_categories_tenant_parent'), 'categories', ['tenant_id', 'parent_id'], unique=False)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('categories', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Ordre d'affichage",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment="URL de l'image de la categorie",
               existing_nullable=True)
    op.alter_column('categories', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID de la categorie parente (NULL = racine)',
               existing_nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Description de la categorie',
               existing_nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Slug URL-safe unique par tenant',
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nom de la categorie',
               existing_nullable=False)
    op.alter_column('bundle_items', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('bundle_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bundle_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bundle_items', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Ordre d'affichage dans le bundle",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bundle_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantite dans le bundle',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('bundle_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK vers products',
               existing_nullable=False)
    op.alter_column('bundle_items', 'bundle_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK vers product_bundles',
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_api_key_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Adresse IP du client (IPv4/IPv6 via type INET PostgreSQL)',
               existing_comment='Adresse IP du client (IPv4/IPv6) ou valeur test (max 45 chars)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.BIGINT(),
               comment='ID utilisateur (NULL pour actions système automatiques)',
               existing_comment='ID utilisateur (NULL pour actions système automatiques ou API key)',
               existing_nullable=True)
    op.drop_column('audit_logs', 'api_key_id')
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Actif (False = supprimé logiquement)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('api_keys', 'tenant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID du tenant (organisation cliente)',
               existing_nullable=False)
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de dernière modification',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'usage_count',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment="Compteur d'utilisations",
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('api_keys', 'last_used_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='IP de la derniere utilisation (IPv4 ou IPv6)',
               existing_nullable=True)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de derniere utilisation',
               existing_nullable=True)
    op.alter_column('api_keys', 'created_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment="ID de l'admin qui a cree la cle",
               existing_nullable=False)
    op.alter_column('api_keys', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date d'expiration (null = pas d'expiration)",
               existing_nullable=True)
    op.alter_column('api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Limite requetes par heure (null = defaut tenant)',
               existing_nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               comment=None,
               existing_comment='Permissions accordees (resource:action)',
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='SHA-256 du full key',
               existing_nullable=False)
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='Prefixe visible pour identification (mk_live_xxxx)',
               existing_nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nom descriptif de la cle API',
               existing_nullable=False)
    # ### end Alembic commands ###
