"""add_audit_log_table_with_immutability_trigger

Revision ID: bd66c5700a41
Revises: 285d45be2c5c
Create Date: 2026-02-12 16:31:27.510854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd66c5700a41'
down_revision: Union[str, None] = '285d45be2c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Clé primaire auto-incrémentée'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='ID utilisateur (NULL pour actions système automatiques)'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='ID tenant (isolation multi-tenant stricte)'),
    sa.Column('action', sa.String(length=50), nullable=False, comment="Type d'action: CREATE, UPDATE, DELETE, SOFT_DELETE, READ_SENSITIVE, LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT"),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment="Type d'entité: Customer, Reservation, Invoice, Product, User, etc."),
    sa.Column('entity_id', sa.BigInteger(), nullable=True, comment="ID de l'entité impactée (NULL pour actions globales type LOGIN)"),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="JSONB modifications: {'field': {'before': old, 'after': new}} pour UPDATE, {'after': data} pour CREATE, {'before': data} pour DELETE"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description humaine de l'action pour lisibilité logs"),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Adresse IP du client (IPv4/IPv6 via type INET PostgreSQL)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent du navigateur/client HTTP'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='UUID de requête HTTP pour corrélation avec logs applicatifs'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp création (immuable, généré par PostgreSQL)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_where=sa.text('entity_type IS NOT NULL AND entity_id IS NOT NULL'))
    op.create_index('idx_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)

    # Créer trigger PostgreSQL pour empêcher UPDATE/DELETE (immutabilité append-only)
    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_audit_log_modification()
        RETURNS TRIGGER AS $$
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                RAISE EXCEPTION 'DELETE on audit_logs is not allowed. Audit logs are append-only for compliance.';
            ELSIF (TG_OP = 'UPDATE') THEN
                RAISE EXCEPTION 'UPDATE on audit_logs is not allowed. Audit logs are immutable for compliance.';
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER prevent_audit_modification
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW
        EXECUTE FUNCTION prevent_audit_log_modification();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Supprimer trigger AVANT de drop table (ordre important)
    op.execute("DROP TRIGGER IF EXISTS prevent_audit_modification ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_modification();")

    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs', postgresql_using='btree', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_audit_tenant_created', table_name='audit_logs', postgresql_using='btree')
    op.drop_index('idx_audit_entity', table_name='audit_logs', postgresql_using='btree', postgresql_where=sa.text('entity_type IS NOT NULL AND entity_id IS NOT NULL'))
    op.drop_index('idx_audit_action_created', table_name='audit_logs', postgresql_using='btree')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
