/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as FideliteRejoindreRouteImport } from './routes/fidelite/rejoindre'
import { Route as AppTransfertsDemandesRouteImport } from './routes/_app/transferts-demandes'
import { Route as AppTransfertsRouteImport } from './routes/_app/transferts'
import { Route as AppReceptionRouteImport } from './routes/_app/reception'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppMargesRouteImport } from './routes/_app/marges'
import { Route as AppInventaireRouteImport } from './routes/_app/inventaire'
import { Route as AppHistoriqueRouteImport } from './routes/_app/historique'
import { Route as AppFournisseursRouteImport } from './routes/_app/fournisseurs'
import { Route as AppEtlImportsRouteImport } from './routes/_app/etl-imports'
import { Route as AppEtlDashboardRouteImport } from './routes/_app/etl-dashboard'
import { Route as AppEtlConflitsRouteImport } from './routes/_app/etl-conflits'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppTransfertsIndexRouteImport } from './routes/_app/transferts/index'
import { Route as AppFideliteIndexRouteImport } from './routes/_app/fidelite/index'
import { Route as AppEtlImportsIndexRouteImport } from './routes/_app/etl-imports/index'
import { Route as AppTransfertsNouveauRouteImport } from './routes/_app/transferts/nouveau'
import { Route as AppTransfertsIdRouteImport } from './routes/_app/transferts/$id'
import { Route as AppFideliteRewardsRouteImport } from './routes/_app/fidelite/rewards'
import { Route as AppFideliteMembresRouteImport } from './routes/_app/fidelite/membres'
import { Route as AppEtlImportsIdRouteImport } from './routes/_app/etl-imports/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const FideliteRejoindreRoute = FideliteRejoindreRouteImport.update({
  id: '/fidelite/rejoindre',
  path: '/fidelite/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfertsDemandesRoute = AppTransfertsDemandesRouteImport.update({
  id: '/transferts-demandes',
  path: '/transferts-demandes',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfertsRoute = AppTransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionRoute = AppReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppMargesRoute = AppMargesRouteImport.update({
  id: '/marges',
  path: '/marges',
  getParentRoute: () => AppRoute,
} as any)
const AppInventaireRoute = AppInventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppFournisseursRoute = AppFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AppRoute,
} as any)
const AppEtlImportsRoute = AppEtlImportsRouteImport.update({
  id: '/etl-imports',
  path: '/etl-imports',
  getParentRoute: () => AppRoute,
} as any)
const AppEtlDashboardRoute = AppEtlDashboardRouteImport.update({
  id: '/etl-dashboard',
  path: '/etl-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEtlConflitsRoute = AppEtlConflitsRouteImport.update({
  id: '/etl-conflits',
  path: '/etl-conflits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfertsIndexRoute = AppTransfertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransfertsRoute,
} as any)
const AppFideliteIndexRoute = AppFideliteIndexRouteImport.update({
  id: '/fidelite/',
  path: '/fidelite/',
  getParentRoute: () => AppRoute,
} as any)
const AppEtlImportsIndexRoute = AppEtlImportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEtlImportsRoute,
} as any)
const AppTransfertsNouveauRoute = AppTransfertsNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => AppTransfertsRoute,
} as any)
const AppTransfertsIdRoute = AppTransfertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTransfertsRoute,
} as any)
const AppFideliteRewardsRoute = AppFideliteRewardsRouteImport.update({
  id: '/fidelite/rewards',
  path: '/fidelite/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppFideliteMembresRoute = AppFideliteMembresRouteImport.update({
  id: '/fidelite/membres',
  path: '/fidelite/membres',
  getParentRoute: () => AppRoute,
} as any)
const AppEtlImportsIdRoute = AppEtlImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEtlImportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/etl-conflits': typeof AppEtlConflitsRoute
  '/etl-dashboard': typeof AppEtlDashboardRoute
  '/etl-imports': typeof AppEtlImportsRouteWithChildren
  '/fournisseurs': typeof AppFournisseursRoute
  '/historique': typeof AppHistoriqueRoute
  '/inventaire': typeof AppInventaireRoute
  '/marges': typeof AppMargesRoute
  '/pos': typeof AppPosRoute
  '/reception': typeof AppReceptionRoute
  '/transferts': typeof AppTransfertsRouteWithChildren
  '/transferts-demandes': typeof AppTransfertsDemandesRoute
  '/fidelite/rejoindre': typeof FideliteRejoindreRoute
  '/etl-imports/$id': typeof AppEtlImportsIdRoute
  '/fidelite/membres': typeof AppFideliteMembresRoute
  '/fidelite/rewards': typeof AppFideliteRewardsRoute
  '/transferts/$id': typeof AppTransfertsIdRoute
  '/transferts/nouveau': typeof AppTransfertsNouveauRoute
  '/etl-imports/': typeof AppEtlImportsIndexRoute
  '/fidelite/': typeof AppFideliteIndexRoute
  '/transferts/': typeof AppTransfertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/etl-conflits': typeof AppEtlConflitsRoute
  '/etl-dashboard': typeof AppEtlDashboardRoute
  '/fournisseurs': typeof AppFournisseursRoute
  '/historique': typeof AppHistoriqueRoute
  '/inventaire': typeof AppInventaireRoute
  '/marges': typeof AppMargesRoute
  '/pos': typeof AppPosRoute
  '/reception': typeof AppReceptionRoute
  '/transferts-demandes': typeof AppTransfertsDemandesRoute
  '/fidelite/rejoindre': typeof FideliteRejoindreRoute
  '/etl-imports/$id': typeof AppEtlImportsIdRoute
  '/fidelite/membres': typeof AppFideliteMembresRoute
  '/fidelite/rewards': typeof AppFideliteRewardsRoute
  '/transferts/$id': typeof AppTransfertsIdRoute
  '/transferts/nouveau': typeof AppTransfertsNouveauRoute
  '/etl-imports': typeof AppEtlImportsIndexRoute
  '/fidelite': typeof AppFideliteIndexRoute
  '/transferts': typeof AppTransfertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/etl-conflits': typeof AppEtlConflitsRoute
  '/_app/etl-dashboard': typeof AppEtlDashboardRoute
  '/_app/etl-imports': typeof AppEtlImportsRouteWithChildren
  '/_app/fournisseurs': typeof AppFournisseursRoute
  '/_app/historique': typeof AppHistoriqueRoute
  '/_app/inventaire': typeof AppInventaireRoute
  '/_app/marges': typeof AppMargesRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reception': typeof AppReceptionRoute
  '/_app/transferts': typeof AppTransfertsRouteWithChildren
  '/_app/transferts-demandes': typeof AppTransfertsDemandesRoute
  '/fidelite/rejoindre': typeof FideliteRejoindreRoute
  '/_app/etl-imports/$id': typeof AppEtlImportsIdRoute
  '/_app/fidelite/membres': typeof AppFideliteMembresRoute
  '/_app/fidelite/rewards': typeof AppFideliteRewardsRoute
  '/_app/transferts/$id': typeof AppTransfertsIdRoute
  '/_app/transferts/nouveau': typeof AppTransfertsNouveauRoute
  '/_app/etl-imports/': typeof AppEtlImportsIndexRoute
  '/_app/fidelite/': typeof AppFideliteIndexRoute
  '/_app/transferts/': typeof AppTransfertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/etl-conflits'
    | '/etl-dashboard'
    | '/etl-imports'
    | '/fournisseurs'
    | '/historique'
    | '/inventaire'
    | '/marges'
    | '/pos'
    | '/reception'
    | '/transferts'
    | '/transferts-demandes'
    | '/fidelite/rejoindre'
    | '/etl-imports/$id'
    | '/fidelite/membres'
    | '/fidelite/rewards'
    | '/transferts/$id'
    | '/transferts/nouveau'
    | '/etl-imports/'
    | '/fidelite/'
    | '/transferts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/dashboard'
    | '/etl-conflits'
    | '/etl-dashboard'
    | '/fournisseurs'
    | '/historique'
    | '/inventaire'
    | '/marges'
    | '/pos'
    | '/reception'
    | '/transferts-demandes'
    | '/fidelite/rejoindre'
    | '/etl-imports/$id'
    | '/fidelite/membres'
    | '/fidelite/rewards'
    | '/transferts/$id'
    | '/transferts/nouveau'
    | '/etl-imports'
    | '/fidelite'
    | '/transferts'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/etl-conflits'
    | '/_app/etl-dashboard'
    | '/_app/etl-imports'
    | '/_app/fournisseurs'
    | '/_app/historique'
    | '/_app/inventaire'
    | '/_app/marges'
    | '/_app/pos'
    | '/_app/reception'
    | '/_app/transferts'
    | '/_app/transferts-demandes'
    | '/fidelite/rejoindre'
    | '/_app/etl-imports/$id'
    | '/_app/fidelite/membres'
    | '/_app/fidelite/rewards'
    | '/_app/transferts/$id'
    | '/_app/transferts/nouveau'
    | '/_app/etl-imports/'
    | '/_app/fidelite/'
    | '/_app/transferts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FideliteRejoindreRoute: typeof FideliteRejoindreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelite/rejoindre': {
      id: '/fidelite/rejoindre'
      path: '/fidelite/rejoindre'
      fullPath: '/fidelite/rejoindre'
      preLoaderRoute: typeof FideliteRejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transferts-demandes': {
      id: '/_app/transferts-demandes'
      path: '/transferts-demandes'
      fullPath: '/transferts-demandes'
      preLoaderRoute: typeof AppTransfertsDemandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transferts': {
      id: '/_app/transferts'
      path: '/transferts'
      fullPath: '/transferts'
      preLoaderRoute: typeof AppTransfertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reception': {
      id: '/_app/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AppReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marges': {
      id: '/_app/marges'
      path: '/marges'
      fullPath: '/marges'
      preLoaderRoute: typeof AppMargesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventaire': {
      id: '/_app/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof AppInventaireRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fournisseurs': {
      id: '/_app/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AppFournisseursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etl-imports': {
      id: '/_app/etl-imports'
      path: '/etl-imports'
      fullPath: '/etl-imports'
      preLoaderRoute: typeof AppEtlImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etl-dashboard': {
      id: '/_app/etl-dashboard'
      path: '/etl-dashboard'
      fullPath: '/etl-dashboard'
      preLoaderRoute: typeof AppEtlDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etl-conflits': {
      id: '/_app/etl-conflits'
      path: '/etl-conflits'
      fullPath: '/etl-conflits'
      preLoaderRoute: typeof AppEtlConflitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transferts/': {
      id: '/_app/transferts/'
      path: '/'
      fullPath: '/transferts/'
      preLoaderRoute: typeof AppTransfertsIndexRouteImport
      parentRoute: typeof AppTransfertsRoute
    }
    '/_app/fidelite/': {
      id: '/_app/fidelite/'
      path: '/fidelite'
      fullPath: '/fidelite/'
      preLoaderRoute: typeof AppFideliteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etl-imports/': {
      id: '/_app/etl-imports/'
      path: '/'
      fullPath: '/etl-imports/'
      preLoaderRoute: typeof AppEtlImportsIndexRouteImport
      parentRoute: typeof AppEtlImportsRoute
    }
    '/_app/transferts/nouveau': {
      id: '/_app/transferts/nouveau'
      path: '/nouveau'
      fullPath: '/transferts/nouveau'
      preLoaderRoute: typeof AppTransfertsNouveauRouteImport
      parentRoute: typeof AppTransfertsRoute
    }
    '/_app/transferts/$id': {
      id: '/_app/transferts/$id'
      path: '/$id'
      fullPath: '/transferts/$id'
      preLoaderRoute: typeof AppTransfertsIdRouteImport
      parentRoute: typeof AppTransfertsRoute
    }
    '/_app/fidelite/rewards': {
      id: '/_app/fidelite/rewards'
      path: '/fidelite/rewards'
      fullPath: '/fidelite/rewards'
      preLoaderRoute: typeof AppFideliteRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fidelite/membres': {
      id: '/_app/fidelite/membres'
      path: '/fidelite/membres'
      fullPath: '/fidelite/membres'
      preLoaderRoute: typeof AppFideliteMembresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/etl-imports/$id': {
      id: '/_app/etl-imports/$id'
      path: '/$id'
      fullPath: '/etl-imports/$id'
      preLoaderRoute: typeof AppEtlImportsIdRouteImport
      parentRoute: typeof AppEtlImportsRoute
    }
  }
}

interface AppEtlImportsRouteChildren {
  AppEtlImportsIdRoute: typeof AppEtlImportsIdRoute
  AppEtlImportsIndexRoute: typeof AppEtlImportsIndexRoute
}

const AppEtlImportsRouteChildren: AppEtlImportsRouteChildren = {
  AppEtlImportsIdRoute: AppEtlImportsIdRoute,
  AppEtlImportsIndexRoute: AppEtlImportsIndexRoute,
}

const AppEtlImportsRouteWithChildren = AppEtlImportsRoute._addFileChildren(
  AppEtlImportsRouteChildren,
)

interface AppTransfertsRouteChildren {
  AppTransfertsIdRoute: typeof AppTransfertsIdRoute
  AppTransfertsNouveauRoute: typeof AppTransfertsNouveauRoute
  AppTransfertsIndexRoute: typeof AppTransfertsIndexRoute
}

const AppTransfertsRouteChildren: AppTransfertsRouteChildren = {
  AppTransfertsIdRoute: AppTransfertsIdRoute,
  AppTransfertsNouveauRoute: AppTransfertsNouveauRoute,
  AppTransfertsIndexRoute: AppTransfertsIndexRoute,
}

const AppTransfertsRouteWithChildren = AppTransfertsRoute._addFileChildren(
  AppTransfertsRouteChildren,
)

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEtlConflitsRoute: typeof AppEtlConflitsRoute
  AppEtlDashboardRoute: typeof AppEtlDashboardRoute
  AppEtlImportsRoute: typeof AppEtlImportsRouteWithChildren
  AppFournisseursRoute: typeof AppFournisseursRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppInventaireRoute: typeof AppInventaireRoute
  AppMargesRoute: typeof AppMargesRoute
  AppPosRoute: typeof AppPosRoute
  AppReceptionRoute: typeof AppReceptionRoute
  AppTransfertsRoute: typeof AppTransfertsRouteWithChildren
  AppTransfertsDemandesRoute: typeof AppTransfertsDemandesRoute
  AppFideliteMembresRoute: typeof AppFideliteMembresRoute
  AppFideliteRewardsRoute: typeof AppFideliteRewardsRoute
  AppFideliteIndexRoute: typeof AppFideliteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEtlConflitsRoute: AppEtlConflitsRoute,
  AppEtlDashboardRoute: AppEtlDashboardRoute,
  AppEtlImportsRoute: AppEtlImportsRouteWithChildren,
  AppFournisseursRoute: AppFournisseursRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppInventaireRoute: AppInventaireRoute,
  AppMargesRoute: AppMargesRoute,
  AppPosRoute: AppPosRoute,
  AppReceptionRoute: AppReceptionRoute,
  AppTransfertsRoute: AppTransfertsRouteWithChildren,
  AppTransfertsDemandesRoute: AppTransfertsDemandesRoute,
  AppFideliteMembresRoute: AppFideliteMembresRoute,
  AppFideliteRewardsRoute: AppFideliteRewardsRoute,
  AppFideliteIndexRoute: AppFideliteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FideliteRejoindreRoute: FideliteRejoindreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
